"""Compose a per-employee daily brief and render it to HTML.

Section assembly is deterministic (temporal/ + relevance/); only the connective prose for
each section is generated by the LLM. The HTML file is the prototype deliverable
(data/reports/{as_of}/{branch}_{name}.html).
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from store_brief.extract.schema import ReportContext, ReportSections
from store_brief.llm import prompts
from store_brief.relevance import retrieve, rerank
from store_brief.temporal import diff, expiring, timeline

_TEMPLATES = Path(__file__).parent / "templates"
_env = Environment(loader=FileSystemLoader(str(_TEMPLATES)), autoescape=select_autoescape())


def build_context(employee, events, as_of: date, llm, index=None, use_rerank=False) -> ReportContext:
    relevant = retrieve.candidate_events(employee, events, index=index)
    if use_rerank:
        relevant = rerank.rerank(employee, relevant, llm)

    current = timeline.resolve_current(relevant)
    sections = ReportSections(
        expiring_today=expiring.expiring_on(relevant, as_of),
        new_this_week=expiring.new_since(relevant, as_of, days=7),
        policy_changes=diff.policy_change_pairs(relevant, as_of, days=7),
        current_relevant=current,
    )
    for pair in sections.policy_changes:
        pair["diff"] = diff.describe_policy_change(pair["old"], pair["new"], llm)

    ctx = ReportContext(employee=employee, as_of=as_of, sections=sections)
    ctx.generated_prose = _section_prose(sections, as_of, llm, employee)
    return ctx


def _section_prose(sections: ReportSections, as_of: date, llm, employee) -> dict[str, str]:
    titles = {
        "expiring_today": ("오늘 종료", sections.expiring_today),
        "new_this_week": ("이번주 신규", sections.new_this_week),
        "current_relevant": ("진행 중 / 담당 사안", sections.current_relevant),
    }
    template = (
        prompts.REPORT_SECTION_MANAGER
        if getattr(employee, "is_store_manager", False)
        else prompts.REPORT_SECTION
    )
    prose: dict[str, str] = {}
    for key, (title, items) in titles.items():
        if not items:
            continue
        listing = "\n".join(f"- [{e.type.value}] {e.title}: {e.summary}" for e in items)
        prose[key] = llm.complete(template.format(
            section_title=title, as_of=as_of, items=listing))
    return prose


def render(ctx: ReportContext, out_dir: str) -> str:
    html = _env.get_template("report.html.j2").render(ctx=ctx)
    day_dir = Path(out_dir) / ctx.as_of.isoformat()
    day_dir.mkdir(parents=True, exist_ok=True)
    out = day_dir / f"{ctx.employee.branch}_{ctx.employee.name}.html"
    out.write_text(html, encoding="utf-8")
    return str(out)
